const path = require("path");
const { MessageEmbed, MessageAttachment } = require("discord.js");
const attachment = new MessageAttachment(
  path.join(__dirname, "../assets/images/logo.png"),
  "logo.png"
);
require("dotenv").config();
const https = require("https");
let messageId = null;
let apod = null;
const apodEmbed = new MessageEmbed();
https.get(
  "https://api.nasa.gov/planetary/apod?api_key=" + process.env.NASA_APID_KEY,
  (res) => {
    let data = "";
    res.on("data", (chunk) => {
      data += chunk;
    });
    res.on("end", () => {
      apod = JSON.parse(data);
      apodEmbed
        .setColor("#F0386B")
        .setTitle(apod.title)
        .setURL(apod.url)
        .setDescription(apod.explanation)
        .attachFiles(attachment)
        .setThumbnail("attachment://logo.png")
        .setTimestamp()
        .setFooter(
          "Generated by astronomia with NASA's APOD API",
          "https://www.nasa.gov/sites/default/files/thumbnails/image/nasa-logo-web-rgb.png"
        );
    });
  }
);

require("dotenv").config();

module.exports = {
  name: "apod",
  aliases: ["a"],
  description: "Astronomy Picture of Day",
  messageId: messageId,
  execute(message, args) {
    (async () => {
      await message.channel.send({ files: [apod.url] });
      message.channel.send(apodEmbed).then(async (msg) => {
        messageId = msg.id;
        await msg.react("❤");
      });
    })();
  },
};
