const { MessageEmbed } = require("discord.js");

const https = require("https");
let messageId = null;
let apod = null;
const apodEmbed = new MessageEmbed();
https.get(
  "https://api.nasa.gov/planetary/apod?api_key=disESfdGqWl9IeIEkbYsDmMBVBTDauyKqC6X4juH",
  (res) => {
    let data = "";
    res.on("data", (chunk) => {
      data += chunk;
    });
    res.on("end", () => {
      apod = JSON.parse(data);
      apodEmbed
        .setColor("#0099ff")
        .setTitle(apod.title)
        .setURL("https://discord.js.org/")
        .setDescription(apod.explanation)
        .setThumbnail("https://www.nasa.gov/sites/default/files/thumbnails/image/nasa-logo-web-rgb.png")
        .setTimestamp()
        .setFooter(
          "Generated by astronomia with NASA's APOD API",
          "https://www.nasa.gov/sites/default/files/thumbnails/image/nasa-logo-web-rgb.png"
        );
    });
  }
);

require("dotenv").config();

module.exports = {
  name: "apod",
  aliases: ["a"],
  description: "Astronomy Picture of Day",
  messageId: messageId,
  execute(message, args) {
    
    (async() => {
    await message.channel.send({ files: [apod.url] });
    message.channel.send(apodEmbed)
      .then(async(msg) => {
        messageId = msg.id;
       await msg.react("◀")
       await msg.react("▶")
      })
    })();
  },
};
