const name = "facts";

const path = require("path");
const { MessageAttachment, MessageEmbed } = require("discord.js");
const factsData = require("../assets/factsData");
const commandUsage = require("../support/commandUsage")

const embed = new MessageEmbed();
const attachment = new MessageAttachment(
  path.join(__dirname, "../assets/images/logo.png"), "logo.png"
);
let randomFact = null;

function setEmbed() {
  embed
    .setColor("#F0386B")
    .setTitle(randomFact.title)
    .setDescription(randomFact.description)
    .attachFiles(attachment)
    .setThumbnail("attachment://logo.png")
    .setTimestamp()
    .setFooter(
      "Generated by astronomia",
      "https://www.nasa.gov/sites/default/files/thumbnails/image/nasa-logo-web-rgb.png"
    );
  return embed;
}

module.exports = {
  name,
  aliases: ["f", "fact"],
  description: "Random facts about space",
  execute(message, args, client, db) {
    commandUsage(name, db);
    (async () => {
      randomFact = await factsData[
        Math.floor(Math.random() * factsData.length)
      ];
      const emb = await setEmbed();
      message.channel.send(emb);
    })();
  },
};
