const name = "moonphase";
const path = require("path");
const commandUsage = require("../support/commandUsage");
const { MessageEmbed, MessageAttachment } = require("discord.js");
const axios = require("axios");
const btoa = require("btoa");
const attachment = new MessageAttachment(
  path.join(__dirname, "../assets/images/logo.png"),
  "logo.png"
);
const astronomyKey = btoa(
  `${process.env.ASTRONOMY_APPLICATION_ID}:${process.env.ASTRONOMY_SECRET}`
);
const locationIqKey = process.env.LOCATION_IQ_KEY;

const fetchLatLong = (address, message) => {
  return axios
    .get(
      `https://eu1.locationiq.com/v1/search.php?key=${locationIqKey}&q=${address}&format=json`
    )
    .then((res) => {
      return {
        lat: res.data[0].lat,
        long: res.data[0].lon,
        place: res.data[0].display_name.substring(
          0,
          res.data[0].display_name.indexOf(",")
        ),
      };
    })
    .catch((err) => {
      console.log(err);
      message.channel.send("Something went wrong while fetching data.");
      message.channel.stopTyping();
    });
};

const fetchMoon = (address, message) => {
  return axios
    .post(
      "https://api.astronomyapi.com/api/v2/studio/moon-phase",
      {
        format: "png",
        style: {
          moonStyle: "default",
          backgroundStyle: "solid",
          backgroundColor: "black",
          headingColor: "black",
          textColor: "white",
        },
        observer: {
          latitude: Number(address.lat),
          longitude: Number(address.long),
          date: new Date(),
        },
        view: {
          type: "portrait-simple",
        },
      },
      {
        headers: {
          "X-Requested-With": "XMLHttpRequest",
          Authorization: `Basic ${astronomyKey}`,
        },
      }
    )
    .then((res) => res.data.data.imageUrl)
    .catch((err) => {
      console.log(err);
      message.channel.send("Something went wrong while fetching data.");
      message.channel.stopTyping();
    });
};

module.exports = {
  name,
  aliases: ["moon"],
  description: "Check moon phase",
  async execute(message, args, client, db) {
    commandUsage(name, db);

    if (args.length === 0) {
      message.channel.send("Please enter location. 🌏");
      return;
    }
    message.channel.startTyping();
    const address = args.join("%20");
    const addressDetail = await fetchLatLong(address, message);
    const moonURL = await fetchMoon(addressDetail, message);
    if (moonURL) {
      const moonEmbed = new MessageEmbed()
        .setColor("#F0386B")
        .setTitle(`Moon Phase`)
        .attachFiles(attachment)
        .setThumbnail("attachment://logo.png")
        .addFields(
          {
            name: "📍 " + addressDetail.place,
            value: "\u200b",
            inline: false,
          },
          {
            name: "```Lat - " + Number(addressDetail.lat).toFixed(4) + "```",
            value: `\u200b`,
            inline: true,
          },
          {
            name: "```Long - " + Number(addressDetail.long).toFixed(4) + "```",
            value: `\u200b`,
            inline: true,
          },
          {
            name: `\u200b`,
            value: `\u200b`,
            inline: true,
          }
        )
        .setImage(moonURL)
        .setTimestamp()
        .setFooter(
          "Generated by astronomia with astronomyapi",
          "https://gblobscdn.gitbook.com/spaces%2F-MKQ7_I-c79Ln1c6Chop%2Favatar-1603563866478.png"
        );
      message.channel.send(moonEmbed);
    }
    message.channel.stopTyping();
  },
};
