const name = "movie";

const { MessageEmbed, MessageAttachment } = require("discord.js");
const path = require("path");
const commandUsage = require("../support/commandUsage");

const movies = require("../assets/astronomyMovies");
const attachment = new MessageAttachment(
  path.join(__dirname, "../assets/images/logo.png"),
  "logo.png"
);

module.exports = {
  name,
  aliases: ["movies", "m"],
  description: "Suggest random movie about space.",
  execute(message, args, client, db) {
    commandUsage(name, db);
    const randomMovie = movies[Math.floor(Math.random() * movies.length - 1)];
    const movieEmbed = new MessageEmbed()
      .setColor("#F0386B")
      .setTitle(randomMovie.title)
      .setURL(randomMovie.link)
      .setImage(randomMovie.poster)
      .setDescription("```" + randomMovie.description + "```")
      .addFields(
        {
          name: `⭐ Rating - ${randomMovie.rating}`,
          value: "\u200b",
          inline: true,
        }
      )
      .setTimestamp()
      .attachFiles(attachment)
      .setFooter("Generated by astronomia", "attachment://logo.png");
    message.channel.send(movieEmbed);
  },
};
