const { MessageEmbed, MessageAttachment } = require("discord.js");
const path = require("path");
const movies = require("../assets/astronomyMovies");
const attachment = new MessageAttachment(
  path.join(__dirname, "../assets/images/logo.png"),
  "logo.png"
);

module.exports = {
  name: "movie",
  aliases: ["movies", "m"],
  description: "Suggest random movie about space.",
  execute(message, args) {
    const randomMovie = movies[Math.floor(Math.random() * movies.length - 1)];
    const movieEmbed = new MessageEmbed()
      .setColor("#F0386B")
      .setTitle(randomMovie.title)
      .setURL(randomMovie.link)
      .setImage(randomMovie.poster)
      .setDescription("```" + randomMovie.description + "```")
      .addFields({
        name: '\u200B',
        value: "```json\n Rating - " + randomMovie.rating + "```",
        inline: true
      },
      {
        name: '\u200B',
        value: "\u200B",
        inline: true
      },
      {
        name: '\u200B',
        value: "\u200B",
        inline: true
      })
      .setTimestamp()
      .attachFiles(attachment)
      .setFooter(
        "Generated by astronomia",
        "attachment://logo.png"
      );
    message.channel.send(movieEmbed);
  },
};
