const path = require("path");
const { MessageEmbed, MessageAttachment } = require("discord.js");
const attachment = new MessageAttachment(
  path.join(__dirname, "../assets/images/logo.png"),
  "logo.png"
);
const quotesData = require("../assets/quotesData");

module.exports = {
  name: "quotes",
  aliases: ["q", "quotes", "quotation"],
  description: "Display random quotation.",
  execute(message, args) {
    const randomQuote =
      quotesData[Math.floor(Math.random() * quotesData.length)];
    const quoteEmbed = new MessageEmbed()
      .setColor("#F0386B")
      .setTitle("Quotes")
      .setDescription(`${randomQuote.content}\n\n — ${randomQuote.author}`)
      .attachFiles(attachment)
      .setThumbnail("attachment://logo.png")
      .setTimestamp()
      .setFooter(
        "Generated by astronomia",
        "attachment://logo.png"
      );
    message.channel.send(quoteEmbed);
  },
};
