const name = "quotes";

const path = require("path");
const { MessageEmbed, MessageAttachment } = require("discord.js");
const commandUsage = require("../support/commandUsage")

const attachment = new MessageAttachment(
  path.join(__dirname, "../assets/images/logo.png"),
  "logo.png"
);
const quotesData = require("../assets/quotesData");

module.exports = {
  name,
  aliases: ["q", "quotes", "quotation", "quote"],
  description: "Display random quotation.",
  execute(message, args, client, db) {
    commandUsage(name, db);
    const randomQuote =
      quotesData[Math.floor(Math.random() * quotesData.length)];
    const quoteEmbed = new MessageEmbed()
      .setColor("#F0386B")
      .setTitle("Quotes")
      .setDescription(`${randomQuote.content}`)
      .addField("\u200b", `\`\`\`css\n— ${randomQuote.author}\`\`\``)
      .attachFiles(attachment)
      .setThumbnail("attachment://logo.png")
      .setTimestamp()
      .setFooter(
        "Generated by astronomia",
        "attachment://logo.png"
      );
    message.channel.send(quoteEmbed);
  },
};
