const path = require("path");
const { MessageEmbed, MessageAttachment } = require("discord.js");
const quotesData = require("../assets/quotesData");
const attachment = new MessageAttachment(
  path.join(__dirname, "../assets/images/logo.png"),
  "logo.png"
);
let randomQuote = null;
module.exports = {
  name: "quotes",
  aliases: ["quote", "q"],
  description: "Display random quotes.",
  execute(message, args) {
    randomQuote = quotesData[Math.floor(Math.random() * quotesData.length)];
    const embed = new MessageEmbed()
      .setColor("#F0386B")
      .setTitle("Quotes")
      .setDescription(`${randomQuote.content}\n\n— ${randomQuote.author}`)
      .attachFiles(attachment)
      .setThumbnail("attachment://logo.png")
      .setFooter("Generated by astronomia", "attachment://logo.png");
    message.channel.send(embed);
  },
};
