const { MessageEmbed } = require("discord.js");
const server = new MessageEmbed();

module.exports = {
  name: "server",
  aliases: ["servers"],
  description: "Check version",
  execute(message, args) {
    const { guild } = message;
    server
      .setColor("#F0386B")
      .setTitle(guild.name)
      .addFields(
        {
          name: "Region",
          value: guild.region.charAt(0).toUpperCase() + guild.region.slice(1),
          inline: true,
        },
        {
          name: "Members:",
          value: guild.memberCount,
          inline: true,
        }
      )
      // .setThumbnail(guild.icon)
      .setTimestamp()
      .setFooter("Generated by astronomia");
    message.channel.send(server);
    console.log(guild.createdAt);
  },
};
