const name = "sky";
const { MessageEmbed } = require("discord.js");
const axios = require("axios");
const btoa = require("btoa");
const commandUsage = require("../support/commandUsage");

require("dotenv").config();
const astronomyKey = btoa(
  `${process.env.ASTRONOMY_APPLICATION_ID}:${process.env.ASTRONOMY_SECRET}`
);
const locationIqKey = process.env.LOCATION_IQ_KEY;

const fetchLatLong = (address, message) => {
  return axios
    .get(
      `https://eu1.locationiq.com/v1/search.php?key=${locationIqKey}&q=${address}&format=json`
    )
    .then((res) => {
      return {
        lat: res.data[0].lat,
        long: res.data[0].lon,
      };
    })
    .catch((err) => {
      console.log(err);
      message.channel.send("Something went wrong while fetching data.");
      message.channel.stopTyping();
    });
};

const fetchSky = (latLong, style, message) => {
  return axios
    .post(
      "https://api.astronomyapi.com/api/v2/studio/star-chart",
      {
        style: style || "navy",
        observer: {
          latitude: Number(latLong.lat),
          longitude: Number(latLong.long),
          date: "2020-11-20",
        },
        view: {
          type: "area",
          parameters: {
            position: {
              equatorial: {
                rightAscension: 0,
                declination: Number(latLong.lat),
              },
            },
            zoom: 6,
          },
        },
      },
      {
        headers: {
          "X-Requested-With": "XMLHttpRequest",
          Authorization: `Basic ${astronomyKey}`,
        },
      }
    )
    .then((res) => res.data.data.imageUrl)
    .catch((err) => {
      console.log(err);
      message.channel.send("Something went wrong while fetching data.");
      message.channel.stopTyping();
    });
};

module.exports = {
  name,
  aliases: ["s", "skyview"],
  description: "Returns a sky view of a selected location.",
  async execute(message, args, client, db) {
    commandUsage(name, db);

    if (args.length === 0) {
      message.channel.send("Please enter location. 🌏");
      return;
    }
    let style = "";
    let address = args.join("%20");
    if (args[0].match(/(red)|(black)|(navy)|(white)/g)) {
      if (args[0] === "black") {
        args[0] = "default";
      }
      if (args[0] === "white") {
        args[0] = "inverted";
      }
      style = args[0];
      address = args.splice(1).join("%20");
    }
    message.channel.startTyping();
    const latLong = await fetchLatLong(address, message);
    const mapURL = await fetchSky(latLong, style, message);
    if (mapURL) {
      const skyEmbed = new MessageEmbed()
        .setColor("#F0386B")
        .setTitle(`Sky view`)
        .setImage(mapURL)
        .setTimestamp()
        .setFooter(
          "Generated by astronomia with astronomyapi",
          "https://gblobscdn.gitbook.com/spaces%2F-MKQ7_I-c79Ln1c6Chop%2Favatar-1603563866478.png"
        );
      message.channel.send(skyEmbed);
    }
    message.channel.stopTyping();
  },
};
