const name = "sky";
const { MessageEmbed, MessageAttachment } = require("discord.js");
const axios = require("axios");
const path = require("path");
const btoa = require("btoa");
const commandUsage = require("../support/commandUsage");
const attachment = new MessageAttachment(
  path.join(__dirname, "../assets/images/logo.png"),
  "logo.png"
);
require("dotenv").config();
const astronomyKey = btoa(
  `${process.env.ASTRONOMY_APPLICATION_ID}:${process.env.ASTRONOMY_SECRET}`
);
const locationIqKey = process.env.LOCATION_IQ_KEY;

const fetchLatLong = (address, message) => {
  return axios
    .get(
      `https://eu1.locationiq.com/v1/search.php?key=${locationIqKey}&q=${address}&format=json`
    )
    .then((res) => {
      return {
        lat: res.data[0]?.lat,
        long: res.data[0]?.lon,
        place: res.data[0]?.display_name.substring(
          0,
          res.data[0].display_name.indexOf(",")
        ),
      };
    })
    .catch((err) => {
      console.log(err.response.status);
      message.channel.send("Location is not given or invalid.");
      message.channel.stopTyping();
    });
};

const fetchSky = (latLong, style, message) => {
  return axios
    .post(
      "https://api.astronomyapi.com/api/v2/studio/star-chart",
      {
        style: style || "navy",
        observer: {
          latitude: Number(latLong?.lat),
          longitude: Number(latLong?.long),
          date: new Date(),
        },
        view: {
          type: "area",
          parameters: {
            position: {
              equatorial: {
                rightAscension: 0,
                declination: Number(latLong?.lat),
              },
            },
            zoom: 4,
          },
        },
      },
      {
        headers: {
          "X-Requested-With": "XMLHttpRequest",
          Authorization: `Basic ${astronomyKey}`,
        },
      }
    )
    .then((res) => res.data.data.imageUrl)
    .catch((err) => {
      console.log(err.response.status);
      message.channel.send("Something went wrong. Can't generate map.");
      message.channel.stopTyping();
    });
};

module.exports = {
  name,
  aliases: ["s", "skyview"],
  description: "Returns a sky view of a selected location.",
  async execute(message, args, client, db) {
    commandUsage(name, db);

    if (args.length === 0) {
      message.channel.send("Please enter location. 🌏");
      return;
    }
    let style = "";
    let address = args.join("%20");
    if (args[0].match(/(red)|(black)|(navy)|(white)/g)) {
      if (args[0] === "black") {
        args[0] = "default";
      }
      if (args[0] === "white") {
        args[0] = "inverted";
      }
      style = args[0];
      address = args.splice(1).join("%20");
    }

    message.channel.startTyping();
    const addressDetail = await fetchLatLong(address, message);
    let mapURL;
    if (addressDetail) {
      mapURL = await fetchSky(addressDetail, style, message);
    }
    if (mapURL) {
      const skyEmbed = new MessageEmbed()
        .setColor("#F0386B")
        .setTitle(`Sky view`)
        .setImage(mapURL)
        .attachFiles(attachment)
        .setThumbnail("attachment://logo.png")
        .addFields(
          {
            name: "📍 " + addressDetail.place,
            value: "\u200b",
            inline: false,
          },
          {
            name: "```Lat - " + Number(addressDetail.lat).toFixed(4) + "```",
            value: `\u200b`,
            inline: true,
          },
          {
            name: "```Long - " + Number(addressDetail.long).toFixed(4) + "```",
            value: `\u200b`,
            inline: true,
          },
          {
            name: `\u200b`,
            value: `\u200b`,
            inline: true,
          }
        )
        .setTimestamp()
        .setFooter(
          "Generated by astronomia with astronomyapi",
          "https://gblobscdn.gitbook.com/spaces%2F-MKQ7_I-c79Ln1c6Chop%2Favatar-1603563866478.png"
        );
      message.channel.send(skyEmbed);
    }
    message.channel.stopTyping();
  },
};
