require("dotenv").config();
const path = require("path");
const { MessageEmbed, MessageAttachment } = require("discord.js");
const attachment = new MessageAttachment(
  path.join(__dirname, "../assets/images/logo.png"),
  "logo.png"
);
const axios = require("axios");
module.exports = {
  name: "wallpaper",
  aliases: ["w", "wallpapers"],
  description: "Download space wallpapers.",
  execute(message, args) {
    (async () => {
      if (args[0] === "realistic") {
        const randomPage = Math.floor(Math.random() * 10);
        const randomImage = Math.floor(Math.random() * 14);
        axios
          .get(
            `https://api.pexels.com/v1/search/?page=${randomPage}&per_page=15&query=space`,
            {
              headers: {
                Authorization: process.env.PEXEL_API_KEY,
              },
            }
          )
          .then((res) => {
            const picEmbed = new MessageEmbed()
              .setColor("#F0386B")
              .setTitle("Download from pexel")
              .setImage(res.data.photos[randomImage].src.large)
              .setURL(res.data.photos[randomImage].url)
              .attachFiles(attachment)
              .setTimestamp()
              .setFooter(
                "Generated by astronomia with Pexel's API",
                "attachment://logo.png"
              );
            message.channel.send(picEmbed);
          })
          .catch((err) => {
            console.log(err);
            message.channel.send(
              "We couldn't find the wallpaper. Please try again."
            );
          });
      } else {
        const gen = await message.channel.send("Generating...");
        const randomPage = Math.floor(Math.random() * 80);
        axios
          .get(
            `https://wall.alphacoders.com/api2.0/get.php?auth=${process.env.WALLPAPER_API_KEY}&method=search&term=space&page=${randomPage}`
          )
          .then((res) => {
            const randomImage =  Math.floor(
              Math.random() * res.data.wallpapers.length
            );
             message.channel.send({
              files: [res.data.wallpapers[randomImage].url_image],
            });
          });
        setTimeout(() => {
          gen.delete();
        }, 3000);
      }
    })();
  },
};
