const puppeteer = require("puppeteer");
const { MessageEmbed } = require("discord.js");

let currentArticle = null;
let previousArticle = null;
module.exports = {
  name: "getPlanetaryNews",
  description: "Get latest news from https://www.planetary.org/articles.",
  execute(client) {
    (async () => {
      const browser = await puppeteer.launch();
      const page = await browser.newPage();
      await page.goto("https://www.planetary.org/articles", {
        waitUntil: "networkidle2",
        timeout: 0,
      });

      const news = await page.evaluate(() => {
        const newsDiv = document.getElementsByClassName(
          "md:flex mb-12 md:mb-6"
        );
        const summaryDiv = newsDiv[0].getElementsByClassName("mt-4");
        const titleDiv = newsDiv[0].getElementsByClassName(
          "text-2xl text-planetary-blue hover:border-b-2 hover:border-planetary-blue leading-tight"
        );
        const imgDiv = newsDiv[0].getElementsByClassName(
          "w-full rounded-lg lazyautosizes lazyloaded"
        );
        return {
          title: titleDiv[0].innerText,
          summary: summaryDiv[0].innerText,
          fullArticle: titleDiv[0].href,
          img: imgDiv[0].currentSrc,
        };
      });
      currentArticle = news;
      await browser.close();
      if (JSON.stringify(currentArticle) != JSON.stringify(previousArticle)) {
        const channel = client.channels.cache.find(
          (channel) => channel.name === "astronomia"
        );
        if (channel) {
          const newsEmbed = new MessageEmbed()
            .setColor("#F0386B")
            .setTitle(currentArticle.title)
            .setURL(currentArticle.fullArticle)
            .setImage(currentArticle.img)
            .setDescription(currentArticle.summary)
            .setTimestamp()
            .setFooter(
              "Generated by astronomia",
              "https://www.nasa.gov/sites/default/files/thumbnails/image/nasa-logo-web-rgb.png"
            );
          channel.send(newsEmbed);
          previousArticle = currentArticle;
        }
      }
    })();
  },
};
