const { SlashCommandBuilder } = require("@discordjs/builders");
const { EmbedBuilder } = require("discord.js");
const axios = require("axios");

module.exports = {
  data: new SlashCommandBuilder().setName("apod").setDescription("NASA Astronomy Picture of the Day"),
  cooldown: 6,
  async execute(interaction) {
    await interaction.deferReply();
    try {
      const url = `https://api.nasa.gov/planetary/apod?api_key=${process.env.NASA_APID_KEY}`;
      const { data } = await axios.get(url);
      
      console.log("APOD data received:", { 
        title: data.title, 
        media_type: data.media_type, 
        url: data.url,
        hdurl: data.hdurl 
      });
      
      if (data.media_type === "video") {
        await interaction.editReply(data.url);
        return;
      }
      
      // Use hdurl if available, otherwise fallback to url
      const imageUrl = data.hdurl || data.url;
      
      const embed = new EmbedBuilder()
        .setColor("#F0386B")
        .setTitle(data.title)
        .setDescription(`${data.explanation}`)
        .setURL(data.url)
        .setImage(imageUrl)
        .setTimestamp(new Date(data.date))
        .setFooter({
          text: "Generated by Astronomia with NASA's APOD API",
          iconURL: "https://www.nasa.gov/sites/default/files/thumbnails/image/nasa-logo-web-rgb.png",
        });
        
      await interaction.editReply({ embeds: [embed] });
    } catch (err) {
      console.error("APOD Error:", err.response?.data || err.message);
      await interaction.editReply("Failed to fetch APOD. Please try again later.");
    }
  },
};

